server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      password: 123456
      username: root
      url: jdbc:mysql://localhost:3306/h5_price?serverTimezone=UTC&useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.base.finance.model
logging:
  config: classpath:logback-spring.xml